services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - log_server
    networks:
      - logging_network

  log_server:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    expose:
      - "5000"
    networks:
      - logging_network

networks:
  logging_network:
    driver: bridge
